# https://github.com/linuxserver/docker-digikam
---
services:
  digikam:
    image: lscr.io/linuxserver/digikam:latest
    container_name: digikam
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SUBFOLDER=/ #optional
    volumes:
      - "${BASEDIR}/custom/services:/custom-services.d:ro"
      - config:/config
      - photo_cameras:/config/Pictures/cameras:ro
      - photo_work:/config/Pictures/tera
      - photo_trash:/config/Pictures/.dtrash
    ports:
      - ${KASMVNC_PORT}:3000
    restart: unless-stopped
volumes:
  config:
    external: true
    name: digikam_config
  photo_cameras:
    external: true
    name: photo_cameras
  photo_work:
    external: true
    name: photo_work
  photo_trash:
    external: true
    name: photo_trash
