# https://github.com/linuxserver/docker-digikam
---
services:
  digikam:
    image: lscr.io/linuxserver/digikam:latest
    container_name: digikam
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SUBFOLDER=/ #optional
    volumes:
      - config:/config
      - "${BASEDIR}/custom/services:/custom-services.d:ro"
      - "${PHOTO_CAMERAS}"
      - "${PHOTO_WORK}"
      - "${PHOTO_TRASH}"
    ports:
      - ${KASMVNC_PORT}:3000
    restart: unless-stopped
volumes:
  config:
    external: true
    name: "${DIGIKAM_CONFIG}"
